### ISSUE TITLE
Choose seamstress and schedule fittings

### ISSUE THREAD

**Issue by huetingj** [huetingj/Wedding-planning#1]
- [x] Decide on seamstress — one recommended by salon, others close to parents? cost differences?
- [x] Call to check availability, appropriate timing and schedule appointments— thinking is First: 3/8 - 3/13 … Second: 4/24 - 4/29
- [x] Talk to mom about trip dates

**Comment by huetingj** [comment]
- Reschedule trip
- Reschedule dress pickup
- Book with Lucy's

**Comment by huetingj** [comment]
MV - March 23 at 1pm
Lucy's - at 4pm
